services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1  # Ensures real-time log output

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - python-app
    environment:
      - FLASK_ENV=development

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=S#cret123
      - POSTGRES_DB=sensordata

volumes:
  postgres_data: